import{a as w,S}from"./assets/vendor-ICl9yzX2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const P="48337516-7b7bbb1aa3939e40fc99ef59c",$="https://pixabay.com/api/";async function m(t,r,n){const s=`${$}?key=${P}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${n}`;return(await w.get(s)).data}function q({webformatURL:t,largeImageURL:r,tags:n,likes:s,views:e,comments:o,downloads:i}){return`
      <a href="${r}" class="gallery-item">
        <img src="${t}" alt="${n}" loading="lazy" />
        <div class="info">
          <p class="info-item"><span>Likes</span><b>${s}</b></p>
          <p class="info-item"><span>Views</span><b>${e}</b></p>
          <p class="info-item"><span>Comments</span><b>${o}</b></p>
          <p class="info-item"><span>Downloads</span><b>${i}</b></p>
        </div>
      </a>
    `}const v=document.querySelector("#search-form"),h=document.querySelector(".gallery"),g=document.querySelector(".loader"),a=document.querySelector(".load-more");let d="",c=1;const f=9;let p=0,y;v.addEventListener("submit",E);a.addEventListener("click",C);function b(){g.style.display="block"}function u(){g.style.display="none"}function l(t){iziToast.error({title:"",message:t,position:"topRight",timeout:5e3,backgroundColor:"#f14646",class:"custom-toast"})}async function E(t){t.preventDefault();const r=t.currentTarget.elements.searchQuery.value.trim();if(!r){l("Please enter a search query.");return}d=r,c=1,O(),a.style.display="none",b();try{const n=await m(d,c,f);if(u(),n.hits.length===0){l("Sorry, there are no images matching<br>your search query. Please, try again!");return}p=n.totalHits,L(n.hits),y=new S(".gallery a"),y.refresh(),n.hits.length<p&&(a.style.display="block")}catch{u(),l("Something went wrong. Please try again later.")}}async function C(){c+=1,a.style.display="none",b();try{const t=await m(d,c,f);u(),L(t.hits),y.refresh(),c*f>=p?(a.style.display="none",l("We're sorry, but you've reached the end of search results.")):a.style.display="block",H()}catch{u(),l("Something went wrong. Please try again later.")}}function L(t){const r=t.map(q).join("");h.insertAdjacentHTML("beforeend",r)}function O(){h.innerHTML=""}function H(){const{height:t}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
